### ISSUE TITLE
Issues about raw data process

### ISSUE THREAD

**Issue by HongxuanZhang** [qinjr/RankFlow#1]
Hi there,
 
I am very interested in the RankFlow project, but some problems occurred during the execution of your code.
 
I used the ml-1m data set, use the corresponding process file to process the raw data of ml-1m dataset. After that , I executed the warmup.py using the ml-1m dataset and dssm model, but it tells me that there is a missing file named "data/ml-1m/feateng_data/train_set_point.pkl' "file, I haven't found any python script that can generate such a file. What should I do?
 
Any response is greatly appreciated，thanks！

**Comment by qinjr** [comment]
Pls run the dataset.py in the code folder as 
```
python dataset.py -d [dataset_name]
```
Sorry, I forgot to add the instruction in README.

**Comment by HongxuanZhang** [comment]
It works! Many thanks!

And actually，It seems that there is no corresponding config file in RankFlow/configs/model_configs of PNN model. Would you mind checking it ?

**Comment by qinjr** [comment]
PNN is actually COLD in the project. 
In the COLD paper, it is a PNN model with feature group selection (SE block). As we are not concerned with the efficiency issue of the pre-ranking model in the offline experiments, we implemented PNN as COLD w/o the feature group selection ("SE block" in the COLD paper).

**Comment by HongxuanZhang** [comment]
Thanks! But I have encountered a new bug.

When I use the cascade structure of "DSSM, FM, DeepFM" to run joint training on the data set ML-1M, the program reports the following bug:

![image](https://user-images.githubusercontent.com/42672185/207810788-5fe034e3-9a71-449a-9cc2-7d5ea87f4ec9.png)


I changed the corresponding functon's “replace” parameter to "True", and the code can successfully complete the joint training. But I still wonder if this behavior will affect the training process? If so, may I ask how to solve the above bug?

**Comment by qinjr** [comment]
Forgot to remove some redundant dev codes.
should use
```
x_user_neg, x_item_neg, label_neg = self._get_teacher_neg_data(data_t)
x_user_pos, x_item_pos, label_pos = self._get_teacher_pos_data()
```
joint_trainer.py has been updated.

**Comment by HongxuanZhang** [comment]
OK！ Many thanks for your help!

**Comment by HongxuanZhang** [comment]
Hi there. When I try to use youtubednn model with tmall dataset, it reports a bug that hist_dict_train.pkl not exists. I didn't find it in dataset.py, but I find the inner function _process_hist()_ in tmall's process_tmall.py, which is is commented out. 

How can I generate the file hist_dict_train.pkl ?
